# Generated by Django 3.0.8 on 2020-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logbook", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="logbook", name="class_sec"),
        migrations.AddField(
            model_name="logbook",
            name="log_class",
            field=models.CharField(
                choices=[
                    ("nursery", "Nursery"),
                    ("lkg", "LKG"),
                    ("ukg", "UKG"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                ],
                default="1",
                max_length=9,
                verbose_name="class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logbook",
            name="log_section",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                default="C",
                max_length=3,
                verbose_name="section",
            ),
            preserve_default=False,
        ),
    ]
